feat: add Docker installation steps to deployment script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,6 +63,21 @@ jobs:
       - name: Deploy on EC2
         run: |
           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
+# 1.           install docker if not installed
+             if ! command -v docker &> /dev/null; then
+               echo "Docker not found. Installing..."
+               sudo apt update
+               sudo apt install -y docker.io
+               sudo systemctl enable docker
+               sudo systemctl start docker
+               sudo usermod -aG docker $USER
+               newgrp docker
+             else
+               echo "Docker is already installed."
+             fi
+
+
+# 2.          spin up docker container with the server
             docker pull $ACTUAL_IMAGE_NAME
             docker stop myapp || true
             docker rm myapp || true
